[package]
name = "geyser-grpc-plugin-client"
version = "0.1.0"
authors = ["Jito Foundation <team@jito.network>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
crossbeam = "0.8.2"
log = "0.4"
lru = "0.8.1"
native-tls = "0.2"
prost = "0.11.6"
prost-types = "0.11.6"
rand = "0.7"
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.68"

jito-solana-sdk = { git = "https://github.com/jito-foundation/jito-solana.git", tag = "v1.13.6-jito", package = "solana-sdk", optional = true }

solana-sdk = "~1.13"

thiserror = "1.0.37"
tokio = { version = "1", features = ["full"] }
tonic = { version = "0.8.3", features = ["tls"] }

[build-dependencies]
tonic-build = "0.8.4"

[features]
jito-solana = ["jito-solana-sdk"]
