[package]
name = "jito-geyser-protos"
version = "0.0.2"
authors = ["Jito Foundation <team@jito.network>"]
license = "Apache-2.0"
edition = "2021"
description = "Jito's Solana geyser protobufs and helper libraries"

[dependencies]
bincode = "1.3.3"
jito-solana-account-decoder = { git = "https://github.com/jito-foundation/jito-solana.git", tag = "v1.14.17-jito", package = "solana-account-decoder", optional = true }
jito-solana-sdk = { git = "https://github.com/jito-foundation/jito-solana.git", tag = "v1.14.17-jito", package = "solana-sdk", optional = true }
jito-solana-transaction-status = { git = "https://github.com/jito-foundation/jito-solana.git", tag = "v1.14.17-jito", package = "solana-transaction-status", optional = true }
prost = "0.11.9"
prost-types = "0.11.9"
serde = "1.0.160"
solana-account-decoder = "~1.14"
solana-sdk = "~1.14"
solana-transaction-status = "~1.14"
tonic = "0.9.2"

[build-dependencies]
tonic-build = "0.9.2"

[features]
jito-solana = ["jito-solana-account-decoder", "jito-solana-sdk", "jito-solana-transaction-status"]
